# Change these first
owner: swindonmakers # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Swindon Makerspace Website
    url: https://www.swindon-makerspace.org/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/swindonmakers/Logo/master/swindon-makerspace-logo-360x120.png
  name: Swindon Makerspace
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Swindon Makerspace
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
